{
	"106": {
		"0401": {
			"name": "PythonCore::Exception",
			"message": "",
			"short_description": "",
			"long_description": "",
			"short_solution": "",
			"long_solution": "",
			"support_link": ""
		}
	}
}